#!/usr/bin/env bash
# my_process management
case "$1" in
start)
  ./manage_my_process &
  echo $! >/var/run/my_process.pid
  disown
  echo "manage_my_process started"
  ;;
stop)
  pkill -f ./manage_my_process
  rm /var/run/my_process.pid
  echo "manage_my_process stopped"
  ;;
restart)
  pkill -f ./manage_my_process
  rm /var/run/my_process.pid  
  ./manage_my_process &
  echo $! >/var/run/my_process.pid
  disown
  echo "manage_my_process started"
  ;;
*)
  echo "Usage: manage_my_process {start|stop|restart}"
esac

