#!/usr/bin/env bash
# infinite loop
echo $$ >/tmp/myscript.pid
while
 echo "To infinity and beyond"
 sleep 2
 trap 'echo "I hate the kill command"&& rm /tmp/myscript.pid && exit' SIGTERM
 trap 'echo "Y U no love me?!"' SIGINT
do true; done

